[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/'
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
localhost = "http://127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
